sudo: required

services:
  - docker

install:
  - docker build -t makeappdev .
  - docker run -d makeappdev

script:
  - docker ps -a
  - docker run makeappdev /bin/sh -c "android list"

notifications:
  email: false
